name: mad_bus
description: A state or event bus (stream manager) organized by topics
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  rxdart: ^0.27.6
